 CONFIGURACION DE LA APLICACION SOFTWARELOGISTIC
# ============================================================

# Nombre de la aplicacion
spring.application.name=softwarelogistic-api


# ============================================================
# CONEXION CON MYSQL
# ============================================================

# Base de datos que utilizara nuestra aplicacion
spring.datasource.url=jdbc:mysql://localhost:3306/software_logistic

# Usuario de MySQL
spring.datasource.username=root

# Contrase\u00f1a de MySQL
# Si tu usuario root no tiene contrase\u00f1a, se deja vacio
spring.datasource.password=

# Driver JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ============================================================
# JPA / HIBERNATE
# ============================================================

# Hibernate valida que las entidades coincidan con las tablas.
# No modifica ni elimina nuestra base de datos.
spring.jpa.hibernate.ddl-auto=validate

# Mostrar las consultas SQL en la consola durante desarrollo
spring.jpa.show-sql=true

# Formatear las consultas SQL para facilitar su lectura
spring.jpa.properties.hibernate.format_sql=true


# ============================================================
# SERVIDOR WEB
# ============================================================

# Puerto donde funcionara nuestra API
server.port=8080